### ISSUE TITLE
Does not implement CTCP FEETPICS

### ISSUE THREAD

**Issue by fstd** [leannemwolf/IRCrobot#9]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when clients do not implement CTCP FEETPICS.

**Describe the solution you'd like**
Upon receiving a CTCP FEETPICS command, the bot should reply with a CTCP FEETPICS response followed by a base64-ed blob of the original authors feet pics in JPEG format.

**Describe alternatives you've considered**
I've considered numerous out of band channels of obtaining feet pics with no success whatsoever, including manual attempts.  CTCP seems like an appropriate standardized way to solve the matter once and for all.

**Comment by kichimi** [comment]
Feel free to submit a pull request with a fix

For now there are various online services that should serve as a fine alternative, such as https://instafeet.com/
